---
title: "Scoring Rules for GEE"
author: "Dimitris Rizopoulos"
date: "`r Sys.Date()`"
output:
  rmarkdown::html_vignette:
    toc: true
vignette: >
  %\VignetteIndexEntry{Scoring Rules for GEE}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
library("cvGEE")
library("geepack")
library("lattice")
library("splines")
```

## Scoring Rules
### Definition

## Examples
### Linear versus non-linear model

```{r, models_Ex1}
pbc2$serBilirD <- as.numeric(pbc2$serBilir > 1.2)
gm1 <- geeglm(serBilirD ~ year * drug, 
              family = binomial(), data = pbc2, id = id, 
              corstr = "exchangeable")

gm2 <- geeglm(serBilirD ~ ns(year, 3, Boundary.knots = c(0, 10)) * drug, 
              family = binomial(), data = pbc2, id = id, 
              corstr = "exchangeable")
```

```{r, cv_gee_Ex1}
plot_data <- cv_gee(gm1, return_data = TRUE)
plot_data$linear <- plot_data$.score
plot_data$non_linear <- unlist(cv_gee(gm2))
```

```{r, plot_Ex1, eval = TRUE, fig.align = "center", fig.width = 8.5, fig.height = 7.5}
xyplot(linear + non_linear ~ year | .rule, data = plot_data, 
       type = "smooth", auto.key = TRUE, layout = c(3, 1),
       scales = list(y = list(relation = "free")),
       xlab = "Follow-up time (years)", ylab = "Scoring Rules")
```


### Working correlation matrix

```{r, models_Ex2}
aids$lowCD4 <- aids$CD4 < sqrt(150)
aids$obstimef <- factor(aids$obstime)
fm1 <- geeglm(lowCD4 ~ obstimef, family = binomial(), data = aids, 
              id = patient, corstr = "independence")

fm2 <- geeglm(lowCD4 ~ obstimef, family = binomial(), data = aids, 
              id = patient, corstr = "exchangeable")

fm3 <- geeglm(lowCD4 ~ obstimef, family = binomial(), data = aids, 
              id = patient, corstr = "ar1")

fm4 <- geeglm(lowCD4 ~ obstimef, family = binomial(), data = aids, 
              id = patient, corstr = "unstructured")
```

```{r, cv_gee_Ex2}
plot_data <- cv_gee(fm1, return_data = TRUE)
plot_data$independence <- plot_data$.score
plot_data$exchangeable <- unlist(cv_gee(fm2))
plot_data$ar1 <- unlist(cv_gee(fm3))
plot_data$unstructured <- unlist(cv_gee(fm4))
```

```{r, plot_Ex2, eval = TRUE, fig.align = "center", fig.width = 8.5, fig.height = 7.5}
xyplot(independence + exchangeable + ar1 + unstructured ~ obstime | .rule, 
       data = plot_data, type = "smooth", auto.key = TRUE, layout = c(3, 1),
       scales = list(y = list(relation = "free")),
       xlab = "Follow-up time (months)", ylab = "Scoring Rules")
```
